function loaduser() { setTimeout(() => { informacoes() }, 500) }

function informacoes() { db.collection(localStorage.getItem("empresa") + "usuarios").where("email", "==", localStorage.getItem("email")).get().then(n => { n.forEach(n => { document.getElementById("empresainput").value = n.data().empresa, document.getElementById("cargo").value = n.data().cargo, document.getElementById("usuario").value = n.data().usuario, document.getElementById("habilidades").value = n.data().habilidadesp + ", " + n.data().habilidadess, document.getElementById("setor").value = n.data().setor, document.getElementById("nome").value = n.data().nome, document.getElementById("email").value = n.data().email, document.getElementById("recado").value = n.data().descricao, localStorage.setItem("idusuario", n.id) }) }).catch(n => { console.log("Error getting documents: ", n) }) }

function update() { db.collection(localStorage.getItem("empresa") + "usuarios").doc(localStorage.getItem("idusuario")).update({ nome: document.getElementById("nome").value, cargo: document.getElementById("cargo").value, email: document.getElementById("email").value, setor: document.getElementById("setor").value, usuario: document.getElementById("usuario").value }).then(() => { Swal.fire({ showConfirmButton: !1, icon: "success", title: "Parabens", text: "Seus dados foram atualizados", footer: "" });
        db.collection("usuarios").doc(localStorage.getItem("idusuario")).update({ nome: document.querySelector("#nome").value }).then(() => { console.log("Document successfully updated!") }).catch(n => { console.error("Error updating document: ", n) }); var n = document.querySelector("#nome").value;
        firebase.auth().onAuthStateChanged(function(t) { t ? t.updateProfile({ displayName: n }).then(function() { console.log("Nome atualizado com sucesso!") }).catch(function(n) { console.error("Erro ao atualizar o nome:", n) }) : console.log("Usuário não autenticado.") });
        setTimeout(() => { location.href = "./login.html" }, 1e3) }).catch(n => { console.error("Error updating document: ", n) }) }
var firebaseConfig = { apiKey: "AIzaSyBKa-Bs_f_Jg80zzeRlMLzrTH_0oWP3Jdo", authDomain: "connectwork-c13b2.firebaseapp.com", projectId: "connectwork-c13b2", storageBucket: "connectwork-c13b2.appspot.com", messagingSenderId: "407759011685", appId: "1:407759011685:web:625201a9a6e0b35aba6b8c", measurementId: "G-TC7VG0QJVX" };
firebase.initializeApp(firebaseConfig);
db = firebase.firestore();